---
- name: Configure DMVPN Phase 1 Lab
  hosts: all
  gather_facts: no
  vars:
    # Hub tunnel IPs
    tunnel_ip_hub: 172.16.0.1
    tunnel_ip_spoke1: 172.16.0.2
    tunnel_ip_spoke2: 172.16.0.3
    tunnel_ip_spoke3: 172.16.0.4
    tunnel_mask: 255.255.255.0
    tunnel_key: 100

    # Hub loopback IP (for tunnel source)
    hub_loopback_ip: 10.255.255.1
    hub_loopback_mask: 255.255.255.255

    # Spoke physical interfaces toward hub
    spoke1_intf: Gi2
    spoke2_intf: Gi3
    spoke3_intf: Gi4

  tasks:

    - name: Configure Hub Loopback0 for DMVPN tunnel source
      ios_config:
        lines:
          - interface Loopback0
          - ip address {{ hub_loopback_ip }} {{ hub_loopback_mask }}
          - no shutdown
      when: "'hub' in inventory_hostname"

    - name: Configure Hub Tunnel0 for DMVPN Phase 1 (mGRE)
      ios_config:
        lines:
          - interface Tunnel0
          - ip address {{ tunnel_ip_hub }} {{ tunnel_mask }}
          - no shutdown
          - tunnel source Loopback0
          - tunnel mode gre multipoint
          - tunnel key {{ tunnel_key }}
      when: "'hub' in inventory_hostname"

    - name: Configure Spoke1 Tunnel0 (point-to-point GRE)
      ios_config:
        lines:
          - interface Tunnel0
          - ip address {{ tunnel_ip_spoke1 }} {{ tunnel_mask }}
          - no shutdown
          - tunnel source {{ spoke1_intf }}
          - tunnel mode gre ip
          - tunnel destination {{ tunnel_ip_hub }}
          - tunnel key {{ tunnel_key }}
          - ip route 0.0.0.0 0.0.0.0 {{ tunnel_ip_hub }}
      when: "'spoke1' in inventory_hostname"

    - name: Configure Spoke2 Tunnel0 (point-to-point GRE)
      ios_config:
        lines:
          - interface Tunnel0
          - ip address {{ tunnel_ip_spoke2 }} {{ tunnel_mask }}
          - no shutdown
          - tunnel source {{ spoke2_intf }}
          - tunnel mode gre ip
          - tunnel destination {{ tunnel_ip_hub }}
          - tunnel key {{ tunnel_key }}
          - ip route 0.0.0.0 0.0.0.0 {{ tunnel_ip_hub }}
      when: "'spoke2' in inventory_hostname"

    - name: Configure Spoke3 Tunnel0 (point-to-point GRE)
      ios_config:
        lines:
          - interface Tunnel0
          - ip address {{ tunnel_ip_spoke3 }} {{ tunnel_mask }}
          - no shutdown
          - tunnel source {{ spoke3_intf }}
          - tunnel mode gre ip
          - tunnel destination {{ tunnel_ip_hub }}
          - tunnel key {{ tunnel_key }}
          - ip route 0.0.0.0 0.0.0.0 {{ tunnel_ip_hub }}
      when: "'spoke3' in inventory_hostname"

    - name: Save config if modified
      ios_config:
        save_when: modified

>>>>>>> 71579013ceb74eacfdb5497cbdd634346bfe5746
