---
- name: Create VLANs and configure trunking on all switches
  hosts: all
  gather_facts: no
  connection: ansible.netcommon.network_cli

  vars_files:
    - all.yml   

  vars:
    trunk_interfaces:
      switch1:
        - GigabitEthernet1/0/2   
      switch2:
        - GigabitEthernet1/0/2   
        - GigabitEthernet1/0/3   
      switch3:
        - GigabitEthernet1/0/3   

  tasks:
    - name: Configure VLANs
      cisco.ios.ios_config:
        lines:
          - "vlan {{ item.id }}"
          - "name {{ item.name }}"
      loop: "{{ vlans }}"
      notify: save_config

    - name: Configure trunk interfaces
      cisco.ios.ios_config:
        parents: "interface {{ item }}"
        lines:
          - "switchport"
          - "switchport mode trunk"
          - "switchport trunk allowed vlan 10,20,30,40,50"
          - "spanning-tree portfast trunk"
          - "no shutdown"
      loop: "{{ trunk_interfaces[inventory_hostname] | default([]) }}"
      notify: save_config

  handlers:
    - name: save_config
      cisco.ios.ios_config:
        save_when: modified
