---
- name: Configure SVI on C800v Router
  hosts: all
  gather_facts: no
  connection: network_cli
  vars:
    vlan_id: 100
    svi_mask: 255.255.255.0

  tasks:
    - name: Configure SVI interface
      cisco.ios.ios_config:
        lines:
          - "interface Vlan{{ vlan_id }}"
          - "ip address {{ svi_ip }} {{ svi_mask }}"
          - "no shutdown"

    - name: Save config if modified
      cisco.ios.ios_config:
        save_when: modified