<<<<<<< HEAD
[switches]
SW1 ansible_host=192.168.1.10

[switches:vars]
ansible_network_os=ios
ansible_user=admin
ansible_password=automation
ansible_connection=ansible.netcommon.network_cli
ansible_become=yes
ansible_become_method=enable
=======
[switches]
SW1 ansible_host=192.168.1.10

[switches:vars]
ansible_network_os=ios
ansible_user=admin
ansible_password=automation
ansible_connection=ansible.netcommon.network_cli
ansible_become=yes
ansible_become_method=enable
>>>>>>> 71579013ceb74eacfdb5497cbdd634346bfe5746
ansible_become_password=Automation